/* eslint-disable import/prefer-default-export */
export const MISSION_ACTION_TYPES = {
  FETCH_MISSIONS_START: 'mission/FETCH_MISSIONS_START',
  FETCH_MISSIONS_SUCCESS: 'mission/FETCH_MISSIONS_SUCCESS',
  FETCH_MISSIONS_FAILURE: 'mission/FETCH_MISSIONS_FAILURE',
  TOGGLE_MISSION_RESERVED: 'mission/TOGGLE_MISSION_RESERVED',
};
